### PR TITLE
Latest changes sync to master

### PR DESCRIPTION
**Pull request by ydubinskyi-dac**

### CODE REVIEW

**Review by reddigszymon — APPROVED** [review]

**Comment by arturszachno** [comment]
Accepted

**Review by arturszachno — COMMENTED** [review]
No comments

**Comment by ydubinskyi-dac** [comment]
@arturszachno - please approve this one as it has all latest changes

**Comment by arturszachno** [comment]
Merged

**Comment by arturszachno** [comment]
Rebase an merge

**Pull request merged**
